services:
  - type: web
    name: yourtopshop-portal
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run server
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: PORT
        value: 3001
      - key: DEV
        value: false
      - key: ADMIN_PIN
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false
